apiVersion: v1
kind: Pod
metadata:
  name: web-server-2
spec:
  volumes:
    - name: html
      gitRepo:             
          repository: https://github.com/shashankv02/k8s-training.git
          revision: master
          directory: . 
  containers:
    - name: web-server-2
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html
