apiVersion: v1
kind: Pod
metadata:
  name: web-server-7
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html
    - name: html-generator
      image: generator:latest
      imagePullPolicy: Never
      #envFrom:
      #  - prefix: QUOTE_
      #    configMapRef:
      #        name: generator-config
      #env:
      #  - name: QUOTE_INTERVAL
      #    valueFrom: 
      #      configMapKeyRef:
      #          name: generator-config
      #          key: INTERVAL
      volumeMounts:
        - mountPath: "/root/html"
          name: html
   
